### ISSUE TITLE
需求 自动更新节点信息

### ISSUE THREAD

**Issue by lorki** [ffip/HiPerBridge#47]
启动HiPer前如果配置项内 自动同步节点 （默认开启） 处于开启状态

先请求 https://cert.mcer.cn/point.yml 文件内容

若请求成功则替换 配置文件里面对于区域

若请求失败则直接启动。

新版本配置文件内容格式样本：
```` yaml
# This is the hiper minimization configuration file. - (6.6.9.9/7)
pki:
  ca: "-----BEGIN HIPER CERTIFICATE-----\nnff6hHY99VsTLAiXvExd6eYyKRhcriqlr0O7BR+k6/qcqDQ==\n-----END HIPER CERTIFICATE-----"
  cert: "-----BEGIN HIPER CERTIFICATE-----\nCmY99VsTLAiXvExdQI\n-----END HIPER CERTIFICATE-----"
  key: "-----BEGIN HIPER X25519 PRIVATE KEY-----\nzmYzY99VsTLAiXvExdU=\n-----END HIPER X25519 PRIVATE KEY-----"

# --------------------------------------------------------------------------------------
#                        WARNING >>> AUTO SYNC AREA
# --------------------------------------------------------------------------------------
# The following configuration will change at any time.
# Please do not configure custom content in the above area. 
# If you need to adjust the configuration, please modify the menu to manual mode.
point:
  "6.6.6.6": 
    - "120.92.140.174:65533"
    - "120.92.216.66:65533"
  "6.7.8.9": 
    - "36.158.69.134:31055"
  "7.7.7.7": 
    - "121.62.22.148:65533"
  "7.7.1.1": 
    - "ddns.xiaomckedou233.top:65533"
  "6.6.1.1": 
    - "160.119.69.222:65533"
  "6.6.3.3": 
    - "104.218.235.107:65533"
  "6.6.2.2": 
    - "154.12.53.189:65533"

tower:
  hosts:
    - "6.6.6.6"
    - "6.7.8.9"
    - "7.7.7.7"
    - "7.7.1.1"
    - "6.6.1.1"
    - "6.6.3.3"
    - "6.6.2.2"

relay:
  relays:
    - "6.6.6.6"
    - "6.7.8.9"
    - "7.7.7.7"
    - "7.7.1.1"
    - "6.6.1.1"
    - "6.6.3.3"
    - "6.6.2.2"
# --------------------------------------------------------------------------------------
#                        WARNING <<< AUTO SYNC AREA
# --------------------------------------------------------------------------------------

dns:
  - "6.6.6.6"

````
